host: "::"
port: 7911
redisUrl: ""
logLevel: info
wsPort: 0
enableSsl: 0
sslPath: ./ssl
sslCert: ""
sslKey: ""
trustedProxies:
  - 127.0.0.0/8
  - ::1/128
noConnectCountLimit: ""
ygoproVersion: "0x1362"
altVersions:
  - 2330
  - 2331
useProxy: ""
ygoproPath: ./ygopro
extraScriptPath: ""
deckMainMin: 40
deckMainMax: 60
deckExtraMax: 15
deckSideMax: 15
deckMaxCopies: 3
ocgcoreDebugLog: 0
ocgcoreWasmPath: ""
welcome: ""
enableWindbot: 1
windbotBotlist: ./windbot/bots.json
windbotSpawn: 0
windbotEndpoint: http://127.0.0.1:2399
windbotMyIp: 127.0.0.1
enableReconnect: 1
reconnectTimeout: 180000
hostinfoLflist: 0
hostinfoRule: 0
hostinfoMode: 0
hostinfoDuelRule: 5
hostinfoNoCheckDeck: 0
hostinfoNoShuffleDeck: 0
hostinfoStartLp: 8000
hostinfoStartHand: 5
hostinfoDrawCount: 1
hostinfoTimeLimit: 240
