HOST: "::"
PORT: "7911"
REDIS_URL: ""
LOG_LEVEL: info
WS_PORT: "0"
SSL_PATH: ""
SSL_CERT: ""
SSL_KEY: ""
TRUSTED_PROXIES: 127.0.0.0/8,::1/128
NO_CONNECT_COUNT_LIMIT: ""
ALT_VERSIONS: ""
USE_PROXY: ""
YGOPRO_PATH: ./ygopro
EXTRA_SCRIPT_PATH: ""
HOSTINFO_LFLIST: "0"
HOSTINFO_RULE: "0"
HOSTINFO_MODE: "0"
HOSTINFO_DUEL_RULE: "5"
HOSTINFO_NO_CHECK_DECK: "0"
HOSTINFO_NO_SHUFFLE_DECK: "0"
HOSTINFO_START_LP: "8000"
HOSTINFO_START_HAND: "5"
HOSTINFO_DRAW_COUNT: "1"
HOSTINFO_TIME_LIMIT: "240"
