host: "::"
port: 7911
apiHost: ""
apiPort: 7922
dbHost: ""
dbPort: 5432
dbUser: postgres
dbPass: ""
dbName: srvpro2
dbNoInit: 0
redisUrl: ""
logLevel: info
wsHost: ""
wsPort: 7912
enableSsl: 0
sslPath: ./ssl
sslCert: ""
sslKey: ""
trustedProxies:
  - 127.0.0.0/8
  - ::1/128
noConnectCountLimit: ""
ygoproVersion: "0x1362"
altVersions:
  - 2330
  - 2331
useProxy: ""
ygoproPath: ./ygopro
extraScriptPath: ""
deckMainMin: 40
deckMainMax: 60
deckExtraMax: 15
deckSideMax: 15
deckMaxCopies: 3
ocgcoreDebugLog: 0
ocgcoreWasmPath: ""
welcome: ""
enableTips: 1
tipsGet: ""
tipsGetZh: ""
tipsSplitZh: 0
tipsPrefix: "Tip: "
tipsInterval: 30000
tipsIntervalIngame: 120000
enableWords: 1
wordsGet: ""
enableDialogues: 1
dialoguesGet: http://mercury233.me/ygosrv233/dialogues.json
dialoguesGetCustom: ""
enableBadwords: 1
badwordsGet: ""
enableWindbot: 0
windbotBotlist: ./windbot/bots.json
windbotSpawn: 0
windbotEndpoint: http://127.0.0.1:2399
windbotMyIp: 127.0.0.1
enableChatgpt: 0
chatgptEndpoint: https://api.openai.com
chatgptToken: sk-xxxx
chatgptModel: gpt-4o-mini
chatgptSystemPrompt: 你是{{windbot}}，一名与{{player}}实时互动的游戏对手。玩家当前 locale 是
  {{locale}}，你必须始终使用 {{language}}
  回复（不要混用其他语言）。你的回复应简短、有趣、贴合当前情境，增强玩家沉浸感。避免冗长解释或重复内容，并且每次回复不能超过100个字。
chatgptTokenLimit: 12000
chatgptExtraOpts: {}
enableReconnect: 1
enableCloudReplay: 1
tournamentMode: 0
tournamentModeCheckDeck: 1
challongeEnabled: 0
challongeNoMatchMode: 0
challongePostDetailedScore: 1
challongePostScoreMidduel: 1
challongeCacheTtl: 60000
challongeApiKey: ""
challongeTournamentId: ""
challongeUrl: https://api.challonge.com
blockReplayToPlayer: 0
enableRoomlist: 1
reconnectTimeout: 180000
hidePlayerName: 0
enableRandomDuel: 1
randomDuelBlankPassModes:
  - S
  - M
randomDuelNoRematchCheck: 0
randomDuelRecordMatchScores: 1
randomDuelDisableChat: 0
randomDuelReadyTime: 20
randomDuelHangTimeout: 90
sideTimeoutMinutes: 3
enableMenu: 0
menu:
  "#{menu_random_duel}": ""
  "#{menu_random_duel_match}": M
  "#{menu_ai_duel}": AI
  "#{menu_more}":
    "#{menu_random_duel_single}": S
    "#{menu_random_duel_tag}": T
    "#{menu_ai_duel_match}": AI,M
    "#{menu_ai_duel_tag}": AI,T
    "#{menu_return}": {}
hostinfoLflist: 0
hostinfoRule: 0
hostinfoMode: 0
hostinfoDuelRule: 5
hostinfoNoCheckDeck: 0
hostinfoNoShuffleDeck: 0
hostinfoStartLp: 8000
hostinfoStartHand: 5
hostinfoDrawCount: 1
hostinfoTimeLimit: 240
hostinfoNoWatch: 0
hostinfoAutoDeath: 0
